name: py39c113
channels:
  - defaults
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - python=3.9
  - pytorch
  - cudatoolkit=11.3
  - pip
  - pip:
    - pytorch_lightning
    - torchmetrics
    - pandas
    - numpy
    - sqlalchemy
    - simple_slurm
    - sklearn
    - matplotlib
    - seaborn
    - transformers
    - sqlalchemy_utils